[package]
name = "sawtooth-protos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "2.0"

[build-dependencies]
glob = "0.3.0"
protobuf-codegen-pure = "2.0"
