name: ci
on:
  push:
    branches:
      - main
      - dev
  pull_request:

env:
  # TODO: not sure if needed, seems to also work without them
  ISOLATION_ID: ${{ github.run_id }}
  DISTRO: bionic

jobs:
  test-sawtooth-core:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # needed for `git describe --dirty` when building docker images
        fetch-depth: 0

    - name: Docker version
      run: |
        docker --version
        docker-compose --version

    - name: Build Sawtooth
      run: |
        docker-compose -f docker-compose-installed.yaml build

    - name: Run tests
      run: |
        INSTALL_TYPE="" ./bin/run_tests -i deployment
